#!/usr/bin/env sh
cd server
echo "Running lint checks"
yarn lint:check
echo "Running tests"
yarn test

if [ $? -ne 0 ]; then
    echo There are lint / test errors in the code. Please fix them before pushing. 1>&2
    exit 1
fi

echo "All checks passed. Proceeding with push..."
exit 0

